### ISSUE TITLE
Unfair comparison with other models.

### ISSUE THREAD

**Issue by hengruizhang98** [CRIPAC-DIG/GRACE#1]
In eval.py, train/test split follows a 90% / 10% mannner instead of that of public split. While the baseline models(e.g. DGI) use public split for evaluation.

**Comment by Linyxus** [comment]
Hi, Hengrui. The metrics reported for baseline models were obtained under the identical protocols used for GRACE. Note that the results reported for DGI in our paper (e.g. 82.6 on Cora) is different from the ones in the original paper (e.g. 82.3 in Cora).
