### ISSUE TITLE
How to process the dataset?

### ISSUE THREAD

**Issue by MrsYaoH** [CRIPAC-DIG/GRACE#2]
Hi, author.
I have some confusion about how to process the dataset. In your project, I could not find and understand this method. Can you push your code about processing dataset please? I will appreciate your generousness.

**Comment by Linyxus** [comment]
Hi. Thank you for your interest in our work! We use the dataset loaders provided by [Pytorch Geometric](https://pytorch-geometric.readthedocs.io/en/latest/) to load the datasets (at https://github.com/CRIPAC-DIG/GRACE/blob/master/train.py#L74-L81) into a data object and have no further processing. You may refer to the official [doc](https://pytorch-geometric.readthedocs.io/en/latest/modules/datasets.html) of PyG on dataset loaders and PyG's [examples](https://github.com/rusty1s/pytorch_geometric/tree/master/examples) to get more information.
