### ISSUE TITLE
Your requirements are not fine

### ISSUE THREAD

**Issue by mhadnanali** [CRIPAC-DIG/GRACE#3]
I think you should mention all the required versions to compile your codes. 
There is no version information of these below, as a result I can not compile your codes. 
torch-scatter
torch-sparse
torch-cluster
torch-spline

You can see from the screenshot, torch-sparce is already installed but it still says there is an import error. I think this is because of the version issue. kindly state the correct versions. I want to use your work in my literature and paper. 

![image](https://user-images.githubusercontent.com/15828557/134610750-e7016c52-9223-41ec-9e0d-325c30c62d3a.png)

**Comment by SXKDZ** [comment]
Thanks for your interest on our work! Our work is built on PyG. Please refer to [this link](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html) for installing all required packages. Also, we have provided a unified package for graph contrastive learning. Please check out [this repository](https://github.com/GraphCL/PyGCL/blob/main/examples/GRACE.py).
